apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-el-hello-listener
spec:
  rules:
  - host: app-listener.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: el-hello-listener
            port:
              number: 8080
  ingressClassName: nginx
  